Add InnerSource SIG Docusaurus Skeleton Build
finos/InnerSource pull request #56
Opened 2022-02-04 14:13 UTC by mcleo-d

## Description
This pull request updates `docusaurus v1` to `docusaurus v2` using the [FINOS Project Blueprint](https://github.com/finos/software-project-blueprint) as a baseline template.

## Additional Changes
As part of this pull request ...

- Markdown file metadata has been added to each page to describe `title` and page `id`
- `resources.md` has been renamed to `awesome.md`
- In `docusaurus.config.js`, `projectName` now equals `InnerSource SIG` and `projectSlug` now equals `innersource-sig`

## Issues Found
In `project-maturity-matrix.md` lines 80 to 82, hyperlinks to the following files were missing, which means `https://` was added to overcome a MD parsing error.

```
- Examples:
  - [Project Lifecycle Definition](https://)
  - [Project Activation](https://)
```

2022-02-14 14:53 UTC, amaltson requested changes
This is really great, thank you for jumping in and getting this going @mcleo-d. I do see a fair amount of changes in one PR, maybe consider breaking this up into a couple of smaller PRs so it's easier to review and merge, maybe something like:

1. PR for the formatting updates, I assume you ran Prettier.
2. PR to add the initial Docsaurus dependency and configuration file.
3. PR to generate the Docusaurus website itself.

2022-02-14 14:53 UTC, amaltson commented on website/.docusaurus/client-modules.js
> +export default [
Does this `.docusaurus` directory need to committed? Or is this generated code that we could add to the `.gitignore`?

2022-02-14 14:53 UTC, amaltson commented on website/sidebars.js
> +module.exports = {
For generating the actual website and HTML to make it a GitHub site, do you prefer having it on the main branch or should we maybe consider having this go to the separate `gh-pages` branch and have a GitHub Action to perform a deployment?

2022-04-11 14:58 UTC, merged

2022-04-11 15:19 UTC, amaltson commented
Hey @mcleo-d, what's the standard deployment mechanism for FINOS Docusaurus projects again? Do you use GitHub Pages or was it Netlify? Thanks!

2022-04-11 16:20 UTC, amaltson commented
Whoops, sorry I missed that!

2022-04-11 16:39 UTC, godds commented
See #60